<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<label for="customer_name"><?= $this->translate('Name') ?></label>
			<input autocomplete="off" id="customer_name" name="customer[name]" class="form-control" size="30" type="text" value="" maxlength="50">
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label for="customer_company"><?= $this->translate('Company') ?></label>
			<input autocomplete="off" id="customer_company" name="customer[company]" class="form-control" size="30" type="text" value="" maxlength="100">
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<label for="customer_vat_number_attributes_identifier_type_id">Tipo de Identificación Fiscal</label>
			<select autocomplete="off" id="customer_vat_number_attributes_identifier_type_id" name="customer[vat_number_attributes][identifier_type_id]" class="form-control">
				<option value="1" selected="selected">NIF</option>
                <option value="2">NIF/IVA (NIF Operador intracomunitario)</option>
                <option value="3">Pasaporte</option>
                <option value="4">Documento oficial de identificación expedido por el país o territorio de residencia</option>
                <option value="5">Certificado de residencia fiscal</option>
                <option value="6">Otro documento probatorio</option>
            </select>
		</div>
		<div class="form-group">
			<label for="customer_vat_number_attributes_identifier">Num. Identificación Fiscal</label>
			<input autocomplete="off" id="customer_vat_number_attributes_identifier" name="customer[vat_number_attributes][identifier]" class="form-control" size="30" type="text" value="" >
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label for="customer_telephone">Teléfono</label>
			<input autocomplete="off" id="customer_telephone" name="customer[telephone]" class="form-control" size="30" type="text" value="" maxlength="50">
		</div>
		<div class="form-group">
			<label for="customer_mobile">Teléfono móvil</label>
			<input autocomplete="off" id="customer_mobile" name="customer[mobile]" class="form-control" size="30" type="text" value="" maxlength="50">
		</div>
		<div class="form-group">
			<label for="customer_email">Correo electrónico</label>
			<input autocomplete="off" id="customer_email" name="customer[email]" class="form-control" size="30" type="text" value="" maxlength="100">
		</div>
	</div>
</div>