<div class="row">
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_via_type_id">Tipo de Vía</label>
			<select autocomplete="off" id="customer_addresses_attributes_0_via_type_id" name="customer[addresses_attributes][0][via_type_id]" class="form-control">
				<option value="">Por favor, elige</option>
                <option value="1">Aldea</option>
                <option value="2">Apartamento</option>
                <option value="3">Area, Arrabal</option>
                <option value="4">Arroyo</option>
                <option value="5">Avenida</option>
                <option value="6">Bajada</option>
                <option value="7">Barranco</option>
                <option value="8">Barrio</option>
                <option value="9">Bloque</option>
                <option value="10">Calle</option>
                <option value="11">Calleja</option>
                <option value="12">Camino</option>
                <option value="13">Carretera</option>
                <option value="14">Caserio</option>
                <option value="15">Colegio</option>
                <option value="16">Colonia</option>
                <option value="17">Conjunto</option>
                <option value="18">Cuesta</option>
                <option value="19">Chalet</option>
                <option value="20">Edificio</option>
                <option value="21">Entrada</option>
                <option value="22">Escalinata</option>
                <option value="23">Explanada</option>
                <option value="24">Extramuros</option>
                <option value="25">Extrarradio</option>
                <option value="26">Ferrocarril</option>
                <option value="27">Glorieta</option>
                <option value="28">Gran Subida</option>
                <option value="29">Grupo</option>
                <option value="30">Huerta</option>
                <option value="31">Jardines</option>
                <option value="32">Lado</option>
                <option value="33">Lugar</option>
                <option value="34">Manzana</option>
                <option value="35">Masia</option>
                <option value="36">Mercado</option>
                <option value="37">Monte</option>
                <option value="38">Muelle</option>
                <option value="39">Municipio</option>
                <option value="40">Parcela</option>
                <option value="41">Parque</option>
                <option value="42">Partida</option>
                <option value="43">Pasaje</option>
                <option value="44">Paseo</option>
                <option value="45">Plaza</option>
                <option value="46">Poblado</option>
                <option value="47">Poligono</option>
                <option value="48">Prolongación</option>
                <option value="49">Puente</option>
                <option value="50">Puerta</option>
                <option value="51">Quinta</option>
                <option value="52">Ramal</option>
                <option value="53">Rambla</option>
                <option value="54">Rampa</option>
                <option value="55">Riera</option>
                <option value="56">Rincón</option>
                <option value="57">Ronda</option>
                <option value="58">Rua</option>
                <option value="59">Salida</option>
                <option value="60">Sector, Sección</option>
                <option value="61">Senda</option>
                <option value="62">Solar, Salón</option>
                <option value="63">Subida</option>
                <option value="64">Terrenos</option>
                <option value="65">Torrente</option>
                <option value="66">Travesia</option>
                <option value="67">Urbanización</option>
                <option value="68">Via</option>
                <option value="69">Via Publica</option>
            </select>
		</div>
	</div>
	<div class="col-md-9">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_via_name"><?= $this->translate('Street name') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_via_name" name="customer[addresses_attributes][0][via_name]" class="form-control" size="30" type="text" value="" maxlength="150">
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_via_number"><?= $this->translate('Street number') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_via_number" name="customer[addresses_attributes][0][via_number]" class="form-control" size="30" type="text" value="" maxlength="5">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_floor"><?= $this->translate('Floor') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_floor" name="customer[addresses_attributes][0][floor]" class="form-control" size="30" type="text" value="" maxlength="5">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_stair"><?= $this->translate('Stair') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_stair" name="customer[addresses_attributes][0][stair]" class="form-control" size="30" type="text" value="" maxlength="10">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_door"><?= $this->translate('Door') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_door" name="customer[addresses_attributes][0][door]" class="form-control" size="30" type="text" value="" maxlength="10">
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_city"><?= $this->translate('City') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_city" name="customer[addresses_attributes][0][city]" class="form-control" size="30" type="text" value="" maxlength="60">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_state"><?= $this->translate('State') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_state" name="customer[addresses_attributes][0][state]" class="form-control" size="30" type="text" value="" maxlength="60">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label for="customer_addresses_attributes_0_postcode"><?= $this->translate('Postal code') ?></label>
			<input autocomplete="off" id="customer_addresses_attributes_0_postcode" name="customer[addresses_attributes][0][postcode]" class="form-control" size="30" type="text" value="" maxlength="10">
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
		<?php 
            $country = $form->get('country');
            $country->setAttribute('class', 'form-control');
            
            echo $this->formLabel($country);
            echo $this->formCountrySelect($country); 
		?>
			<select autocomplete="off" id="customer_addresses_attributes_0_country_id" name="customer[addresses_attributes][0][country_id]" class="form-control">
				<option value="1">Andorra</option>
                <option value="2">Emiratos Árabes Unidos</option>
                <option value="3">Afganistán</option>
                <option value="4">Antigua y Barbuda</option>
                <option value="5">Anguila</option>
                <option value="6">Albania</option>
                <option value="7">Armenia</option>
                <option value="8">Antillas Neerlandesas</option>
                <option value="9">Angola</option>
                <option value="10">Antártida</option>
                <option value="11">Argentina</option>
                <option value="12">Samoa Americana</option>
                <option value="13">Austria</option>
                <option value="14">Australia</option>
                <option value="15">Aruba</option>
                <option value="16">Azerbaiyán</option>
                <option value="17">Bosnia y Hercegovina</option>
                <option value="18">Barbados</option>
                <option value="19">Bangladesh</option>
                <option value="20">Bélgica</option>
                <option value="21">Burkina Faso</option>
                <option value="22">Bulgaria</option>
                <option value="23">Bahráin</option>
                <option value="24">Burundi</option>
                <option value="25">Benín</option>
                <option value="26">Bermudas</option>
                <option value="27">Brunéi</option>
                <option value="28">Bolivia</option>
                <option value="29">Brasil</option>
                <option value="30">Bahamas</option>
                <option value="31">Bután</option>
                <option value="32">Isla Bouvet</option>
                <option value="33">Botsuana</option>
                <option value="34">Bielorrusia</option>
                <option value="35">Belice</option>
                <option value="36">Canadá</option>
                <option value="37">Islas Cocos</option>
                <option value="38">República Democrática del Congo</option>
                <option value="39">República Centroafricana</option>
                <option value="40">Congo</option>
                <option value="41">Suiza</option>
                <option value="42">Costa de Marfil</option>
                <option value="43">Islas Cook</option>
                <option value="44">Chile</option>
                <option value="45">Camerún</option>
                <option value="46">China</option>
                <option value="47">Colombia</option>
                <option value="48">Costa Rica</option>
                <option value="49">Cuba</option>
                <option value="50">Cabo Verde</option>
                <option value="51">Isla Christmas</option>
                <option value="52">Chipre</option>
                <option value="53">República Checa; Chequia</option>
                <option value="54">Alemania</option>
                <option value="55">Yibuti</option>
                <option value="56">Dinamarca</option>
                <option value="57">Dominica</option>
                <option value="58">República Dominicana</option>
                <option value="59">Argelia</option>
                <option value="60">Ecuador</option>
                <option value="61">Estonia</option>
                <option value="62">Egipto</option>
                <option value="63">Sáhara Occidental</option>
                <option value="64">Eritrea</option>
                <option value="65" selected="selected">España</option>
                <option value="66">Etiopía</option>
                <option value="67">Finlandia</option>
                <option value="68">Fiyi</option>
                <option value="69">Islas Malvinas</option>
                <option value="70">Micronesia</option>
                <option value="71">Islas Feroe</option>
                <option value="72">Francia</option>
                <option value="73">Gabón</option>
                <option value="74">Reino Unido</option>
                <option value="75">Granada</option>
                <option value="76">Georgia</option>
                <option value="77">Guayana Francesa</option>
                <option value="78">Ghana</option>
                <option value="79">Gibraltar</option>
                <option value="80">Groenlandia</option>
                <option value="81">Gambia</option>
                <option value="82">Guinea</option>
                <option value="83">Guadalupe</option>
                <option value="84">Guinea Ecuatorial</option>
                <option value="85">Grecia</option>
                <option value="86">Islas Georgia del Sur y Sandwich del Sur</option>
                <option value="87">Guatemala</option>
                <option value="88">Guam</option>
                <option value="89">Guinea-Bissau</option>
                <option value="90">Guyana</option>
                <option value="91">Hong Kong</option>
                <option value="92">Islas Heard y McDonald</option>
                <option value="93">Honduras</option>
                <option value="94">Croacia</option>
                <option value="95">Haití</option>
                <option value="96">Hungría</option>
                <option value="97">Indonesia</option>
                <option value="98">Irlanda</option>
                <option value="99">Israel</option>
                <option value="100">India (la)</option>
                <option value="101">Territorio Británico del Océano Indico</option>
                <option value="102">Iraq</option>
                <option value="103">Irán</option>
                <option value="104">Islandia</option>
                <option value="105">Italia</option>
                <option value="106">Jamaica</option>
                <option value="107">Jordania</option>
                <option value="108">Japón</option>
                <option value="109">Kenia</option>
                <option value="110">Kirguizistán</option>
                <option value="111">Camboya</option>
                <option value="112">Kiribati</option>
                <option value="113">Comoras</option>
                <option value="114">San Cristóbal y Nieves</option>
                <option value="115">Corea del Norte</option>
                <option value="116">Corea del Sur</option>
                <option value="117">Kuwait</option>
                <option value="118">Islas Caimán</option>
                <option value="119">Kazajistán</option>
                <option value="120">Laos</option>
                <option value="121">Líbano</option>
                <option value="122">Santa Lucía</option>
                <option value="123">Liechtenstein</option>
                <option value="124">Sri Lanka</option>
                <option value="125">Liberia</option>
                <option value="126">Lesoto</option>
                <option value="127">Lituania</option>
                <option value="128">Luxemburgo</option>
                <option value="129">Letonia</option>
                <option value="130">Libia</option>
                <option value="131">Marruecos</option>
                <option value="132">Mónaco</option>
                <option value="133">Moldavia</option>
                <option value="134">Madagascar</option>
                <option value="135">Islas Marshall</option>
                <option value="136">Macedonia</option>
                <option value="137">Malí</option>
                <option value="138">Birmania; Myanmar</option>
                <option value="139">Mongolia</option>
                <option value="140">Macao</option>
                <option value="141">Islas Marianas del Norte</option>
                <option value="142">Martinica</option>
                <option value="143">Mauritania</option>
                <option value="144">Montserrat</option>
                <option value="145">Malta</option>
                <option value="146">Mauricio</option>
                <option value="147">Maldivas</option>
                <option value="148">Malaui</option>
                <option value="149">México</option>
                <option value="150">Malasia</option>
                <option value="151">Mozambique</option>
                <option value="152">Namibia</option>
                <option value="153">Nueva Caledonia</option>
                <option value="154">Níger</option>
                <option value="155">Isla Norfolk</option>
                <option value="156">Nigeria</option>
                <option value="157">Nicaragua</option>
                <option value="158">Países Bajos</option>
                <option value="159">Noruega</option>
                <option value="160">Nepal</option>
                <option value="161">Nauru</option>
                <option value="162">Niue</option>
                <option value="163">Nueva Zelanda</option>
                <option value="164">Omán</option>
                <option value="165">Panamá</option>
                <option value="166">Perú</option>
                <option value="167">Polinesia Francesa</option>
                <option value="168">Papúa-Nueva Guinea</option>
                <option value="169">Filipinas</option>
                <option value="170">Pakistán</option>
                <option value="171">Polonia</option>
                <option value="172">San Pedro y Miquelón</option>
                <option value="173">Islas Pitcairn</option>
                <option value="174">Puerto Rico</option>
                <option value="175">Portugal</option>
                <option value="176">Palaos</option>
                <option value="177">Paraguay</option>
                <option value="178">Qatar</option>
                <option value="179">Reunión</option>
                <option value="180">Rumania; Rumanía</option>
                <option value="181">Rusia</option>
                <option value="182">Ruanda</option>
                <option value="183">Arabia Saudí</option>
                <option value="184">Islas Salomón</option>
                <option value="185">Seychelles</option>
                <option value="186">Sudán</option>
                <option value="187">Suecia</option>
                <option value="188">Singapur</option>
                <option value="189">Santa Helena</option>
                <option value="190">Eslovenia</option>
                <option value="191">Svalbard y Jan Mayen</option>
                <option value="192">Eslovaquia</option>
                <option value="193">Sierra Leona</option>
                <option value="194">San Marino</option>
                <option value="195">Senegal</option>
                <option value="196">Somalia</option>
                <option value="197">Surinam</option>
                <option value="198">Santo Tomé y Príncipe</option>
                <option value="199">El Salvador</option>
                <option value="200">Siria</option>
                <option value="201">Suazilandia</option>
                <option value="202">Islas Turcas y Caicos</option>
                <option value="203">Chad</option>
                <option value="204">Territorios Australes Franceses</option>
                <option value="205">Togo</option>
                <option value="206">Tailandia</option>
                <option value="207">Tayikistán</option>
                <option value="208">Tokelau</option>
                <option value="209">Timor Oriental</option>
                <option value="210">Turkmenistán</option>
                <option value="211">Túnez</option>
                <option value="212">Tonga</option>
                <option value="213">Turquía</option>
                <option value="214">Trinidad y Tobago</option>
                <option value="215">Tuvalu</option>
                <option value="216">Taiwán</option>
                <option value="217">Tanzania</option>
                <option value="218">Ucrania</option>
                <option value="219">Uganda</option>
                <option value="220">Islas menores alejadas de los Estados Unidos</option>
                <option value="221">Estados Unidos</option>
                <option value="222">Uruguay</option>
                <option value="223">Uzbekistán</option>
                <option value="224">El Vaticano</option>
                <option value="225">San Vicente y las Granadinas</option>
                <option value="226">Venezuela</option>
                <option value="227">Islas Vírgenes Británicas</option>
                <option value="228">Islas Vírgenes Americanas</option>
                <option value="229">Vietnam</option>
                <option value="230">Vanuatu</option>
                <option value="231">Wallis y Futuna</option>
                <option value="232">Samoa</option>
                <option value="233">Yemen</option>
                <option value="234">Mayotte</option>
                <option value="235">Yugoslavia</option>
                <option value="236">Sudáfrica</option>
                <option value="237">Zambia</option>
                <option value="238">Zimbabue</option>
            </select>
		</div>
	</div>
</div>