<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<?php 
			$name = $form->get('name');
			$name->setAttribute('class', 'form-control');
			$name->setAttribute('required', 'required');
			
			echo $this->formLabel($name);
			echo $this->formText($name);
			?>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<?php 
			$company = $form->get('company');
			$company->setAttribute('class', 'form-control');
			
			echo $this->formLabel($company);
			echo $this->formText($company);
			?>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
		<?php 
			$vat_type = $form->get('vat_type');
			$vat_type->setAttribute('class', 'form-control');
			
			echo $this->formLabel($vat_type);
			echo $this->formSelect($vat_type);
	    ?>
		</div>
		<div class="form-group">
		<?php 
			$vat_number = $form->get('vat_number');
			$vat_number->setAttribute('class', 'form-control');
			
			echo $this->formLabel($vat_number);
			echo $this->formText($vat_number);
	    ?>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
		<?php 
			$phone = $form->get('phone');
			$phone->setAttribute('class', 'form-control');
			
			echo $this->formLabel($phone);
			echo $this->formText($phone);
	    ?>
		</div>
		<div class="form-group">
		<?php 
			$phone = $form->get('mobile');
			$phone->setAttribute('class', 'form-control');
			
			echo $this->formLabel($phone);
			echo $this->formText($phone);
	    ?>
		</div>
		<div class="form-group">
		<?php 
			$email = $form->get('email');
			$email->setAttribute('class', 'form-control');
			
			echo $this->formLabel($email);
			echo $this->formText($email);
	    ?>
		</div>
	</div>
</div>