<div class="row">
	<div class="col-md-12">
		<div class="form-group">
		<?php 
            $street = $form->get('street_1');
            $street->setAttribute('class', 'form-control');
            
            echo $this->formLabel($street);
            echo $this->formText($street); 
		?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="form-group">
		<?php 
            $street = $form->get('street_2');
            $street->setAttribute('class', 'form-control');
            
            echo $this->formLabel($street);
            echo $this->formText($street); 
		?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="form-group">
		<?php 
            $city = $form->get('city');
            $city->setAttribute('class', 'form-control');
            
            echo $this->formLabel($city);
            echo $this->formText($city); 
		?>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
		<?php 
            $state = $form->get('state');
            $state->setAttribute('class', 'form-control');
            
            echo $this->formLabel($state);
            echo $this->formText($state); 
		?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="form-group">
		<?php 
            $postal_code = $form->get('postal_code');
            $postal_code->setAttribute('class', 'form-control');
            
            echo $this->formLabel($postal_code);
            echo $this->formText($postal_code); 
		?>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
		<?php 
            $country = $form->get('country');
            $country->setAttribute('class', 'form-control');
            
            echo $this->formLabel($country);
            echo $this->formCountrySelect($country); 
		?>
		</div>
	</div>
</div>