
<div class="panel panel-default">
	<div class="panel-heading"><?= $this->translate('Customer details') ?></div>
	<div class="panel-body">
		<?= $this->partial('customer/partial/details'); ?>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading"><?= $this->translate('Address') ?></div>
	<div class="panel-body">
		<?= $this->partial('customer/partial/address'); ?>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading"><?= $this->translate('Notes') ?></div>
	<div class="panel-body">
		<?= $this->partial('customer/partial/notes'); ?>
	</div>
</div>